### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by piranna** [bytenode/bytenode#151] opened 2021-08-13 07:49 UTC
Since now Node.js supports source maps when outputting errors, does it makes sense to generate them for `.jsc` files? I know main reason to use `bytenode` is to hide source code when distributed, but it can be useful to have them in case you need to debug a compiled file.

**Comment by piranna** [comment] 2024-03-03 14:24
Any update on this? Any clue how can it be implemented? I think so far source maps are not publicly provided, we are safe...

**Comment by jjeff** [comment] 2024-03-03 17:36
Duplicate of https://github.com/bytenode/bytenode/issues/219

**Closed** 2024-03-04 08:27 UTC
